export HomeSolid from "./home_solid.svg"
export IconArrowBack from "./icon_arrow_back.svg"
export IconBookmarkOutline from "./icon_bookmark_outline.svg"
export IconMark from "./icon_mark.svg"
export IconPaperOutline from "./icon_paper_outline.svg"
export IconProfile from "./icon_profile.svg"
export IconSearch from "./icon_search.svg"
export IconTrash from "./icon_trash.svg"